import type { Plant } from './plant-data';

export const plantsNL: Plant[] = [
    {
        id: 1,
        name: "Appelboom",
        category: "tree",
        scientificName: "Malus domestica",
        description:
            "Een bladverliezende boom die zoete, knapperige appels produceert. Uitstekend om vers te eten en voor koken. Biedt schaduw en leefgebied voor nuttige insecten.",
        position: { x: 25, y: 30 },
        harvestSeason: "Laat Zomer - Herfst",
        sunRequirement: "Volle Zon",
        waterNeeds: "Matig",
        height: "4,5-7,5 meter",
        image: "/apple-tree-with-red-apples.jpg",
        maintenance: "medium",
        optimalConditions: {
            temperature: { min: 15, max: 25 },
            humidity: { min: 50, max: 70 },
            soilPH: { min: 6.0, max: 7.0 },
            soilMoisture: { min: 40, max: 60 },
            sunlightHours: { min: 6, max: 8 },
        },
        currentConditions: {
            stage: "fruiting",
            harvestDays: 45,
            temperature: 22,
            humidity: 58,
            soilPH: 6.5,
            soilMoisture: 52,
            sunlightHours: 7,
            status: "good",
        },
    },
    {
        id: 2,
        name: "Bosbessenstruik",
        category: "shrub",
        scientificName: "Vaccinium corymbosum",
        description:
            "Een productieve struik met zoete, antioxidant-rijke bessen. Heeft de voorkeur voor zure grond en geeft prachtig herfstgebladerte.",
        position: { x: 45, y: 55 },
        harvestSeason: "Zomer",
        sunRequirement: "Volle Zon tot Halfschaduw",
        waterNeeds: "Hoog",
        height: "1,2-1,8 meter",
        image: "/blueberry-bush-with-ripe-blue-berries.jpg",
        maintenance: "medium",
        optimalConditions: {
            temperature: { min: 18, max: 26 },
            humidity: { min: 60, max: 80 },
            soilPH: { min: 4.5, max: 5.5 },
            soilMoisture: { min: 60, max: 80 },
            sunlightHours: { min: 6, max: 8 },
        },
        currentConditions: {
            stage: "fruiting",
            harvestDays: 21,
            temperature: 24,
            humidity: 72,
            soilPH: 5.8,
            soilMoisture: 45,
            sunlightHours: 7,
            status: "good",
        },
    },
    {
        id: 3,
        name: "Rozemarijn",
        category: "herb",
        scientificName: "Rosmarinus officinalis",
        description:
            "Een aromatisch groenblijvend kruid met naaldachtige bladeren. Gebruikt in de keuken en heeft medicinale eigenschappen. Trekt bestuivers aan.",
        position: { x: 70, y: 40 },
        harvestSeason: "Het hele jaar",
        sunRequirement: "Volle Zon",
        waterNeeds: "Laag",
        height: "60-120 cm",
        image: "/rosemary-herb-plant-with-purple-flowers.jpg",
        maintenance: "low",
        optimalConditions: {
            temperature: { min: 15, max: 28 },
            humidity: { min: 40, max: 60 },
            soilPH: { min: 6.0, max: 7.5 },
            soilMoisture: { min: 20, max: 40 },
            sunlightHours: { min: 6, max: 8 },
        },
        currentConditions: {
            stage: "growing",
            harvestDays: 0,
            temperature: 26,
            humidity: 48,
            soilPH: 6.8,
            soilMoisture: 32,
            sunlightHours: 8,
            status: "good",
        },
    },
    {
        id: 4,
        name: "Tomaat",
        category: "vegetable",
        scientificName: "Solanum lycopersicum",
        description:
            "Een warmteseizoen groente die sappige, smaakvolle vruchten produceert. Heeft steun en regelmatig water nodig voor de beste productie.",
        position: { x: 60, y: 70 },
        harvestSeason: "Zomer",
        sunRequirement: "Volle Zon",
        waterNeeds: "Hoog",
        height: "90-180 cm",
        image: "/tomato-plant-with-ripe-red-tomatoes.jpg",
        maintenance: "high",
        optimalConditions: {
            temperature: { min: 20, max: 30 },
            humidity: { min: 60, max: 80 },
            soilPH: { min: 6.0, max: 6.8 },
            soilMoisture: { min: 60, max: 80 },
            sunlightHours: { min: 6, max: 8 },
        },
        currentConditions: {
            stage: "flowering",
            harvestDays: 60,
            temperature: 12,
            humidity: 35,
            soilPH: 5.2,
            soilMoisture: 25,
            sunlightHours: 4,
            status: "critical",
        },
    },
    {
        id: 5,
        name: "Perenboom",
        category: "tree",
        scientificName: "Pyrus communis",
        description:
            "Een mooie bloeiende boom die zoete, sappige peren produceert. Geeft lentebloesem en herfstoogst.",
        position: { x: 35, y: 65 },
        harvestSeason: "Herfst",
        sunRequirement: "Volle Zon",
        waterNeeds: "Matig",
        height: "4,5-6 meter",
        image: "/pear-tree-with-yellow-pears.jpg",
        maintenance: "medium",
        optimalConditions: {
            temperature: { min: 15, max: 25 },
            humidity: { min: 50, max: 70 },
            soilPH: { min: 6.0, max: 7.0 },
            soilMoisture: { min: 40, max: 60 },
            sunlightHours: { min: 6, max: 8 },
        },
        currentConditions: {
            stage: "fruiting",
            harvestDays: 90,
            temperature: 23,
            humidity: 62,
            soilPH: 6.4,
            soilMoisture: 55,
            sunlightHours: 7,
            status: "good",
        },
    },
    {
        id: 6,
        name: "Lavendel",
        category: "herb",
        scientificName: "Lavandula angustifolia",
        description:
            "Een geurig meerjarig kruid met paarse bloemen. Uitstekend voor het aantrekken van bestuivers en heeft kalmerende eigenschappen.",
        position: { x: 80, y: 25 },
        harvestSeason: "Zomer",
        sunRequirement: "Volle Zon",
        waterNeeds: "Laag",
        height: "30-90 cm",
        image: "/purple-lavender.png",
        maintenance: "low",
        optimalConditions: {
            temperature: { min: 18, max: 30 },
            humidity: { min: 30, max: 50 },
            soilPH: { min: 6.5, max: 8.0 },
            soilMoisture: { min: 20, max: 40 },
            sunlightHours: { min: 6, max: 8 },
        },
        currentConditions: {
            stage: "flowering",
            harvestDays: 14,
            temperature: 28,
            humidity: 42,
            soilPH: 7.2,
            soilMoisture: 28,
            sunlightHours: 8,
            status: "good",
        },
    },
    {
        id: 7,
        name: "Frambozenstruik",
        category: "shrub",
        scientificName: "Rubus idaeus",
        description:
            "Een doornige struik die zoete rode bessen produceert. Verspreidt zich via uitlopers en geeft een overvloedige zomeroogst.",
        position: { x: 50, y: 45 },
        harvestSeason: "Zomer",
        sunRequirement: "Volle Zon",
        waterNeeds: "Matig",
        height: "1,2-1,8 meter",
        image: "/raspberry-bush-with-red-raspberries.jpg",
        maintenance: "medium",
        optimalConditions: {
            temperature: { min: 16, max: 24 },
            humidity: { min: 60, max: 80 },
            soilPH: { min: 5.5, max: 6.5 },
            soilMoisture: { min: 50, max: 70 },
            sunlightHours: { min: 6, max: 8 },
        },
        currentConditions: {
            stage: "fruiting",
            harvestDays: 28,
            temperature: 20,
            humidity: 68,
            soilPH: 6.0,
            soilMoisture: 58,
            sunlightHours: 7,
            status: "good",
        },
    },
    {
        id: 8,
        name: "Boerenkool",
        category: "vegetable",
        scientificName: "Brassica oleracea",
        description: "Een voedingsrijk bladgewas dat gedijt in koel weer. Vorst verbetert zelfs de smaak.",
        position: { x: 65, y: 60 },
        harvestSeason: "Herfst - Lente",
        sunRequirement: "Volle Zon tot Halfschaduw",
        waterNeeds: "Matig",
        height: "30-60 cm",
        image: "/kale-plant-with-dark-green-curly-leaves.jpg",
        maintenance: "low",
        optimalConditions: {
            temperature: { min: 10, max: 20 },
            humidity: { min: 50, max: 70 },
            soilPH: { min: 6.0, max: 7.5 },
            soilMoisture: { min: 50, max: 70 },
            sunlightHours: { min: 4, max: 6 },
        },
        currentConditions: {
            stage: "growing",
            harvestDays: 35,
            temperature: 16,
            humidity: 58,
            soilPH: 6.8,
            soilMoisture: 62,
            sunlightHours: 5,
            status: "good",
        },
    },
    {
        id: 9,
        name: "Hazelaar",
        category: "tree",
        scientificName: "Corylus avellana",
        description:
            "Een kleine boom of grote struik die voedzame noten produceert. Geeft vroege voorjaarskatjes en herfstoogst.",
        position: { x: 20, y: 50 },
        harvestSeason: "Herfst",
        sunRequirement: "Volle Zon tot Halfschaduw",
        waterNeeds: "Matig",
        height: "3-4,5 meter",
        image: "/hazelnut-tree-with-nuts.jpg",
        maintenance: "low",
        optimalConditions: {
            temperature: { min: 12, max: 22 },
            humidity: { min: 50, max: 70 },
            soilPH: { min: 6.0, max: 7.5 },
            soilMoisture: { min: 40, max: 60 },
            sunlightHours: { min: 5, max: 7 },
        },
        currentConditions: {
            stage: "growing",
            harvestDays: 120,
            temperature: 19,
            humidity: 64,
            soilPH: 6.6,
            soilMoisture: 48,
            sunlightHours: 6,
            status: "good",
        },
    },
    {
        id: 10,
        name: "Tijm",
        category: "herb",
        scientificName: "Thymus vulgaris",
        description:
            "Een laaggroeiend aromatisch kruid perfect als bodembedekker. Gebruikt in de keuken en trekt nuttige insecten aan.",
        position: { x: 75, y: 35 },
        harvestSeason: "Het hele jaar",
        sunRequirement: "Volle Zon",
        waterNeeds: "Laag",
        height: "15-30 cm",
        image: "/thyme-herb-plant-with-small-leaves.jpg",
        maintenance: "low",
        optimalConditions: {
            temperature: { min: 15, max: 28 },
            humidity: { min: 40, max: 60 },
            soilPH: { min: 6.0, max: 8.0 },
            soilMoisture: { min: 20, max: 40 },
            sunlightHours: { min: 6, max: 8 },
        },
        currentConditions: {
            stage: "growing",
            harvestDays: 0,
            temperature: 24,
            humidity: 52,
            soilPH: 7.0,
            soilMoisture: 30,
            sunlightHours: 7,
            status: "good",
        },
    },
    {
        id: 11,
        name: "Vlierbes",
        category: "shrub",
        scientificName: "Sambucus nigra",
        description: "Een snelgroeiende struik met trossen donkere bessen. Gebruikt voor immuunondersteuning en trekt wilde dieren aan.",
        position: { x: 40, y: 35 },
        harvestSeason: "Laat Zomer",
        sunRequirement: "Volle Zon tot Halfschaduw",
        waterNeeds: "Matig",
        height: "2,4-3,6 meter",
        image: "/elderberry-bush-with-dark-purple-berries.jpg",
        maintenance: "low",
        optimalConditions: {
            temperature: { min: 15, max: 25 },
            humidity: { min: 50, max: 70 },
            soilPH: { min: 5.5, max: 6.5 },
            soilMoisture: { min: 50, max: 70 },
            sunlightHours: { min: 5, max: 7 },
        },
        currentConditions: {
            stage: "fruiting",
            harvestDays: 42,
            temperature: 22,
            humidity: 66,
            soilPH: 6.2,
            soilMoisture: 64,
            sunlightHours: 6,
            status: "good",
        },
    },
    {
        id: 12,
        name: "Sla",
        category: "vegetable",
        scientificName: "Lactuca sativa",
        description: "Een koudseizoen bladgewas perfect voor salades. Groeit snel en kan in opeenvolging worden geplant.",
        position: { x: 55, y: 75 },
        harvestSeason: "Lente - Herfst",
        sunRequirement: "Halfschaduw",
        waterNeeds: "Matig",
        height: "15-30 cm",
        image: "/green-lettuce-plant.png",
        maintenance: "medium",
        optimalConditions: {
            temperature: { min: 10, max: 20 },
            humidity: { min: 50, max: 70 },
            soilPH: { min: 6.0, max: 7.0 },
            soilMoisture: { min: 60, max: 80 },
            sunlightHours: { min: 4, max: 6 },
        },
        currentConditions: {
            stage: "growing",
            harvestDays: 25,
            temperature: 24,
            humidity: 45,
            soilPH: 6.5,
            soilMoisture: 50,
            sunlightHours: 7,
            status: "good",
        },
    },
];
